import JSP000585Complete

#print axioms CatlinCertificates.eight_colours
#print axioms CatlinCertificates.proper_eight_colouring
#print axioms CatlinCertificates.no_independent_triple
#print axioms CatlinCertificates.finite_budget_certificate
#print axioms CatlinCertificates.budget_bound
#print axioms CatlinCertificates.no_feasible_resource_tuple
#print axioms CatlinComplete.mem_inside
#print axioms CatlinComplete.card_inside
#print axioms CatlinComplete.length_ge_two
#print axioms CatlinComplete.length_ge_three
#print axioms CatlinComplete.demand_le_inside
#print axioms CatlinComplete.profile_certificate
#print axioms CatlinComplete.separated_endpoints
#print axioms CatlinComplete.common_in_middle
#print axioms CatlinComplete.cluster_size
#print axioms CatlinComplete.count_le_three
#print axioms CatlinComplete.sum_counts
#print axioms CatlinComplete.full_cluster
#print axioms CatlinComplete.weight_le_demand
#print axioms CatlinComplete.regroup
#print axioms CatlinComplete.regroup_twice
#print axioms CatlinComplete.profileCost_le_budget
#print axioms CatlinComplete.budget_ge_eight
#print axioms CatlinComplete.sum_demand_edges
#print axioms CatlinComplete.total_inside_bound
#print axioms CatlinComplete.subdivision_budget_bound
#print axioms CatlinComplete.colour_fiber_card_le_two
#print axioms CatlinComplete.not_seven_colorable
#print axioms CatlinComplete.chromaticNumber_eq_eight
#print axioms CatlinComplete.no_K8_subdivision
#print axioms CatlinComplete.catlin_counterexample
#print axioms CatlinComplete.seven_exceptional
#print axioms CatlinComplete.seven_detour
#print axioms CatlinComplete.contains_K7_subdivision
#print axioms CatlinComplete.containsCliqueSubdivision_antitone
#print axioms CatlinComplete.containsCliqueSubdivision_iff
#print axioms CatlinComplete.sharp_catlin_counterexample
#print axioms JSP000585.edge_left_mem
#print axioms JSP000585.edge_right_mem
#print axioms JSP000585.edge_lt
#print axioms JSP000585.card_branchSet
#print axioms JSP000585.mem_branchSet
#print axioms JSP000585.branch_branchLabel
#print axioms JSP000585.labels_ne
#print axioms JSP000585.indexedEdge_injective
#print axioms JSP000585.convertedPath_isPath
#print axioms JSP000585.inside_convertedPath
#print axioms JSP000585.containsSubdivision_iff_indexed
#print axioms JSP000585.subdivisionModels_iff
#print axioms JSP000585.catlin_subdivision_iff
#print axioms JSP000585.catlin_sigma_eq_seven
#print axioms JSP000585.catlin_chi_eq_eight
#print axioms JSP000585.catlin_ratio_eq
#print axioms JSP000585.catlin_ratio_gt_one
#print axioms JSP000585.exists_universal_ratio_bound
#print axioms JSP000585.ratio_range_bddAbove
#print axioms JSP000585.extremal_upper_bound
#print axioms JSP000585.catlin_extremal_lower_bound
#print axioms JSP000585.catlin_constant_lower_bound
#print axioms JSP000585.jsp_000585
#print axioms Erdos717.erdos_717
